name: cv-snippets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy~=1.26
    - matplotlib
    - jupyter
    - torch==2.5.1
    - open3d==0.17.0
    - opencv-contrib-python==4.9.0.80
